' OPTION + D to run 
@startuml
class Restaurant {
    id Integer 
    name String
    menus Array<Menu>
    --
    addMenu(<Menu>) 
    deleteMenu(<Menu>)
}
class Menu {
    id Integer 
    title String 
    items Array<Item>
    --
    addItem(<Item>)
    deleteItem(<Item>)
}
class Item {
    id Integer 
    name String 
    price Float  
    createItem(<Name>, <Price>)
    deleteItem(<Item>)
}
Restaurant --{ Menu 
Menu --{ Item 
@enduml  

' Restaurant has many menus
' Menu has many items 

' Menu belongs to Restaurant 
' Item belongs to Menu 